name: Top-Languages Readme

on:
    workflow_dispatch:
    schedule:
        # Runs at 12am UTC
        - cron: '0 0 * * *'

jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
        - uses: ryuanerin/top-languages-readme@master
          with:
            COMMIT_MESSAGE: "Updated the Graph with new Metrics" # Optional
            USERNAME: DIEGOHORVATTI # Optional
            LINE_FORMAT: "$NAME   $SIZE $BAR  $PERCENT" # Optional
            LIST_COUNT: 10 # Optional
            BLOCKS: "░█" # Optional
            BAR_WIDTH: 25 # Optional
            SHOW_TOTAL: false # Optional
            TOP_TOTAL: false # Optional
            SHOW_TOTAL_SEPARATOR: true # Optional
